#!/usr/bin/env bash

shopt -s nullglob globstar

case "$1" in
    --type )
        typeit=1
        shift
        ;;
    --type-and-copy )
        typeit=2
        shift
        ;;
    * )
        typeit=0
        ;;
esac

STARTDIR=${PASSWORD_STORE_DIR-~/.password-store}
BASEDIR=$STARTDIR
DONE=0
LEVEL=0
PREVSELECTION=""
SELECTION=""

while [ "$DONE" -eq 0 ] ; do
  password_files=( "$STARTDIR"/* )
  password_files=( "${password_files[@]#"$STARTDIR"/}" )
  password_files=( "${password_files[@]%.gpg}" )

  if [ "$LEVEL" -ne 0 ] ; then
    password_files=(".." "${password_files[@]}")
  fi
  entry=$(printf '%s\n' "${password_files[@]}" | dmenu -i -l 15)

  echo "entry: $entry"
  if [ -z "$entry" ] ; then
    DONE=1
    exit
  fi

  if [ "$entry" != ".." ] ; then
    PREVSELECTION=$SELECTION
    SELECTION="$SELECTION/$entry"

    # check if another dir
    if [ -d "$STARTDIR/$entry" ] ; then
      STARTDIR="$STARTDIR/$entry"
      LEVEL=$((LEVEL+1))
    else

      # not a directory so it must be a real password entry
      [[ -n "$SELECTION" ]] || exit

      data="$(pass show "$SELECTION" 2>/dev/null)"

      [[ -n "$data" ]] || exit

      case $typeit in
	    0 )
		pass show -c "$SELECTION"
		;;
	    1 )
		pass show "$SELECTION" \
		    | { read -r pass; printf %s "$pass"; } \
		    | xdotool type --clearmodifiers --file -
		;;
	    2 )
		<<<"$data" tail -n +2 | sed -ne '/^login: /I s/^login: // p' | xdotool type --clearmodifiers --file -
		pass show -c "$SELECTION"
		;;
      esac
      DONE=1
    fi

  else
    LEVEL=$((LEVEL-1))
    SELECTION=$PREVSELECTION
    STARTDIR="$BASEDIR/$SELECTION"
  fi
done
